In [15]:
import numpy as np

In [16]:
E = 210
v = 0.3

c11 = E/(1-v**2)
c12 = v*E/(1-v**2)
c44 = 0.5*(c11-c12)


Cvoigt = np.zeros((6,6))
# Input the material constants
Cvoigt[0,0] = c11
Cvoigt[0,1] = c12
Cvoigt[0,2] = c12
Cvoigt[0,3] = 0
Cvoigt[0,4] = 0
Cvoigt[0,5] = 0
Cvoigt[1,1] = c11
Cvoigt[1,2] = c12
Cvoigt[1,3] = 0
Cvoigt[1,4] = 0
Cvoigt[1,5] = 0
Cvoigt[2,2] = c11
Cvoigt[2,3] = 0
Cvoigt[2,4] = 0
Cvoigt[2,5] = 0
Cvoigt[3,3] = c44
Cvoigt[3,4] = 0
Cvoigt[3,5] = 0
Cvoigt[4,4] = c44
Cvoigt[4,5] = 0
Cvoigt[5,5] = c44


# Symmetrize the matrix
for i in range(6):
    for j in range(i,6):
        Cvoigt[j,i] = Cvoigt[i,j]

# Print the matrix
print(Cvoigt)

[[230.76923077  69.23076923  69.23076923   0.           0.
    0.        ]
 [ 69.23076923 230.76923077  69.23076923   0.           0.
    0.        ]
 [ 69.23076923  69.23076923 230.76923077   0.           0.
    0.        ]
 [  0.           0.           0.          80.76923077   0.
    0.        ]
 [  0.           0.           0.           0.          80.76923077
    0.        ]
 [  0.           0.           0.           0.           0.
   80.76923077]]


In [17]:
def mapping(i,j):
    if i==0 and j==0:
        return 0
    elif i==1 and j==1:
        return 1
    elif i==2 and j==2:
        return 2
    elif (i==1 and j==2) or (i==2 and j==1):
        return 3
    elif (i==0 and j==2) or (i==2 and j==0):
        return 4
    elif (i==0 and j==1) or (i==1 and j==0):
        return 5

In [18]:
# Convert to Voigt notation
C = np.zeros((3,3,3,3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            for l in range(3):
                ind1 = mapping(i,j)
                ind2 = mapping(k,l)
                C[i,j,k,l] = Cvoigt[ind1,ind2]

# Print the matrix
print(C)

[[[[230.76923077   0.           0.        ]
   [  0.          69.23076923   0.        ]
   [  0.           0.          69.23076923]]

  [[  0.          80.76923077   0.        ]
   [ 80.76923077   0.           0.        ]
   [  0.           0.           0.        ]]

  [[  0.           0.          80.76923077]
   [  0.           0.           0.        ]
   [ 80.76923077   0.           0.        ]]]


 [[[  0.          80.76923077   0.        ]
   [ 80.76923077   0.           0.        ]
   [  0.           0.           0.        ]]

  [[ 69.23076923   0.           0.        ]
   [  0.         230.76923077   0.        ]
   [  0.           0.          69.23076923]]

  [[  0.           0.           0.        ]
   [  0.           0.          80.76923077]
   [  0.          80.76923077   0.        ]]]


 [[[  0.           0.          80.76923077]
   [  0.           0.           0.        ]
   [ 80.76923077   0.           0.        ]]

  [[  0.           0.           0.        ]
   [  0.      